DATA_DIR = './data'
TRANSFORMER_TYPE = 'bert'
MODEL_NAME = 'microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract'
TRAIN_FILE = 'train_filter.data'
DEV_FILE = 'dev_filter.data'
TEST_FILE = 'test_filter.data'
